// This file is generated automatically. Any changes will be lost!
#include "profiles/linux_native.hpp"

const InvokerProfile linux_native_profile = {
    "linux_native", SyscallAction::Security, PathAccess::Denied,
    {
        { "access", SyscallAction::Allow },
        { "arch_prctl", SyscallAction::Allow },
        { "brk", SyscallAction::Allow },
        { "clock_getres", SyscallAction::Allow },
        { "clock_gettime", SyscallAction::Allow },
        { "close", SyscallAction::Allow },
        { "dup", SyscallAction::Allow },
        { "dup2", SyscallAction::Allow },
        { "dup3", SyscallAction::Allow },
        { "exit", SyscallAction::Allow },
        { "exit_group", SyscallAction::Allow },
        { "fcntl", SyscallAction::Allow },
        { "futex", SyscallAction::Allow },
        { "getcwd", SyscallAction::Allow },
        { "getdents", SyscallAction::Allow },
        { "getdents64", SyscallAction::Allow },
        { "getegid", SyscallAction::Allow },
        { "geteuid", SyscallAction::Allow },
        { "getpid", SyscallAction::Allow },
        { "getppid", SyscallAction::Allow },
        { "getrandom", SyscallAction::Allow },
        { "getrlimit", SyscallAction::Allow },
        { "getrusage", SyscallAction::Allow },
        { "gettid", SyscallAction::Allow },
        { "gettimeofday", SyscallAction::Allow },
        { "getuid", SyscallAction::Allow },
        { "fstat", SyscallAction::Allow },
        { "ioctl", SyscallAction::Allow },
        { "lseek", SyscallAction::Allow },
        { "madvise", SyscallAction::Allow },
        { "mmap", SyscallAction::Allow },
        { "mprotect", SyscallAction::Allow },
        { "mremap", SyscallAction::Allow },
        { "munmap", SyscallAction::Allow },
        { "nanosleep", SyscallAction::Allow },
        { "read", SyscallAction::Allow },
        { "restart_syscall", SyscallAction::Allow },
        { "rt_sigaction", SyscallAction::Allow },
        { "rt_sigprocmask", SyscallAction::Allow },
        { "rt_sigreturn", SyscallAction::Allow },
        { "sigaction", SyscallAction::Allow },
        { "sigaltstack", SyscallAction::Allow },
        { "sigprocmask", SyscallAction::Allow },
        { "sigreturn", SyscallAction::Allow },
        { "sysinfo", SyscallAction::Allow },
        { "time", SyscallAction::Allow },
        { "write", SyscallAction::Allow },
        { "writev", SyscallAction::Allow },
        { "kill", SyscallAction::Deny },
        { "tkill", SyscallAction::Deny },
        { "tgkill", SyscallAction::Deny },
        { "lstat64", SyscallAction::CheckPath },
        { "lstat", SyscallAction::CheckPath },
        { "newlstat", SyscallAction::CheckPath },
        { "newstat", SyscallAction::CheckPath },
        { "open", SyscallAction::CheckPath },
        { "openat", SyscallAction::CheckPath },
        { "stat64", SyscallAction::CheckPath },
        { "stat", SyscallAction::CheckPath },
        { "readlink", SyscallAction::CheckPath },
    },
    {
        { "/lib/", PathAccess::ReadOnly },
        { "/lib32/", PathAccess::ReadOnly },
        { "/lib64/", PathAccess::ReadOnly },
        { "/usr/lib/", PathAccess::ReadOnly },
        { "/usr/lib32/", PathAccess::ReadOnly },
        { "/usr/lib64/", PathAccess::ReadOnly },
        { "/usr/libexec/", PathAccess::ReadOnly },
        { "/usr/local/lib/", PathAccess::ReadOnly },
        { "/usr/local/lib32/", PathAccess::ReadOnly },
        { "/usr/local/lib64/", PathAccess::ReadOnly },
        { "/usr/local/libexec/", PathAccess::ReadOnly },
        { "/usr/share/", PathAccess::ReadOnly },
        { "/usr/local/share/", PathAccess::ReadOnly },
        { "/etc/ld.so.preload", PathAccess::ReadOnly },
        { "/etc/ld.so.cache", PathAccess::ReadOnly },
        { "/dev/zero", PathAccess::ReadOnly },
        { "/dev/null", PathAccess::ReadOnly },
        { "/dev/tty", PathAccess::ReadOnly },
        { "/dev/urandom", PathAccess::ReadOnly },
        { "/etc/passwd", PathAccess::ReadOnly },
        { "/etc/group", PathAccess::ReadOnly },
        { "/proc/self/", PathAccess::ReadOnly },
    },
};
